version: 1
update_configs:
    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - "NdagiStanley"
    default_labels:
      - "python packages"
  # Keep requirements.txt up to date as soon as
  # new versions are published to the pypi registry
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
